### ISSUE TITLE
cannot edit favorites

### ISSUE THREAD

**Issue by synthnassizer** [assen-totin/android-icecast-player#2]
Hi there, 
thank you for a very practical app!
I have (times and times again) made mistakes while typing icecast server addresses in "add station" and I only realize once I try to play a station. They new stations I usually add into favorites, so in order to alter , I have to delete the favorite station and re-add from scratch. editing favorites would be great.

**Comment by assen-totin** [comment]
HI!
I normally use copy/paste when manually adding stations, hence never needed this... but it may well be worth looking into this. Should not be way too difficult anyway.

**Comment by synthnassizer** [comment]
Hm,
what use say apo c-p makes sense, but I tend to listen to a few
off-the-internet icecast servers.
So I cannot just grab an address usually :)

Thanks!

**Comment by assen-totin** [comment]
Editing a station from the main list and from Favourites was added in the new 5.0 release.
