### ISSUE TITLE
icecast player crashing randomly in android 5

### ISSUE THREAD

**Issue by synthnassizer** [assen-totin/android-icecast-player#3]
I am using android 5 and the app works fine for about 1-2hours, then it crashes and I have to restart it. Once it is restarted it will go on playing for 5-6h no problem. Then eventually, i'll stop listening - which usually coincides with me leaving my work place and close the app. The next day the same happens. This is weird. I wonder if anyone else has problems with this app crashing like that.

**Comment by assen-totin** [comment]
That's a bit bizarre... When this happens next time, can you give me here the date and time it happened? I do see some exceptions in Android 5.0, but they are not in the playback-related code... so having a timestamp from you will help hit the exact error and troubleshoot it.

**Comment by synthnassizer** [comment]
Hi there!
what sort of timestamp are you looking into ? just the time of the android
clock?
I have no idea of app development in android (or how would a timestamp
help), so if you refer to something else, please specify :)

Thank you for the swift response!

**Comment by assen-totin** [comment]
Hi,

When the app crashes next time, just note the date and time (be it the time your phone displays or your computer, or your wrist watch...) and add it to the ticket - together with your time zone (or country + state + city so that I may figure the time zone).

Thanks in advance!

**Comment by assen-totin** [comment]
Closing as no info received. You're welcome to try the new 5.0 version with interface improvements and even more radio stations.
